FROM registry.access.redhat.com/ubi8/ubi-minimal:8.6
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work/application
EXPOSE 9090
CMD ["/work/application", "-Dquarkus.http.host=0.0.0.0"]