version: '3.8'

services:
  dish-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:9090/Dish
      - QUARKUS_DATASOURCE_USERNAME=postgres
      - QUARKUS_DATASOURCE_PASSWORD=admin123
    depends_on:
      - postgres
    networks:
      - dish-network

  postgres:
    image: postgres:17
    ports:
      - "9090:9090"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=Dish
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["-p", "9090"]
    networks:
      - dish-network

volumes:
  postgres-data:

networks:
  dish-network:
    driver: bridge