version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=meals_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/meals_db
      - QUARKUS_DATASOURCE_USERNAME=admin
      - QUARKUS_DATASOURCE_PASSWORD=admin
volumes:
  postgres-data: